apiVersion: v1
kind: Service
metadata:
  name: enterprise-system-145111-d2z1-service
spec:
  selector:
    app: enterprise-system-145111-d2z1
  ports:
  - port: 80
    targetPort: 8000
  type: ClusterIP
